# k8scli user@ip
sys.k8scli:wy@133.133.135.56
sys.namespace:crdb1
sys.pods:crdb1-0, crdb1-1, crdb1-2
# sys.leaderzone:zone1
sys.zones:zone1,zone2,zone3
sys.zone1.pods:crdb1-0
sys.zone2.pods:crdb1-1
sys.zone3.pods:crdb1-2
sys.storage.pods=crdb1-0,crdb1-1,crdb1-2
sys.faults:random_zone_storage_all_fail.yaml
sys.storage.volumePath:/cockroach/cockroach-data/
sys.faulttime:10

db=crdb
driver=org.postgresql.Driver
application=CRDB
conn=jdbc:postgresql://133.133.135.56:30171/tpccdb
user=tpccdb
password=

warehouses=40
loadWorkers=4
monkeys=4
sutThreads=16
maxDeliveryBGThreads=0
maxDeliveryBGPerWarehouse=0
rampupMins=2
rampupSUTMins=1
rampupTerminalMins=0
runMins=3
reportIntervalSecs=1
resultIntervalSecs=1
restartSUTThreadProbability=0.0
keyingTimeMultiplier=0.8
thinkTimeMultiplier=0.8
traceTerminalIO=false
paymentWeight=0.0
orderStatusWeight=0.0
deliveryWeight=0.0
stockLevelWeight=0.0
storeWeight=0.0
rollbackPercent=0.0
reportScript=./generateReport.py -t report_simple.html
