sys.k8scli=wy@133.133.135.56
sys.namespace=pg
sys.pods=postgresql-1,postgresql-2,postgresql-3
sys.zones=zone1
sys.zone1.pods=postgresql-1,postgresql-2,postgresql-3
sys.storage.pods=postgresql-1,postgresql-2,postgresql-3
sys.faults=random_zone_storage_one_kill.yaml
sys.storage.volumePath=/var/lib/postgresql/data
sys.faulttime=1

db=postgres
driver=org.postgresql.Driver
application=Generic
conn=jdbc:postgresql://133.133.135.56:32162/tpccdb
user=tpccdb
password=123@Test

warehouses=100
loadWorkers=8
monkeys=1
sutThreads=1
maxDeliveryBGThreads=0
maxDeliveryBGPerWarehouse=0
rampupMins=2
rampupSUTMins=1
rampupTerminalMins=1
runMins=3
reportIntervalSecs=1
resultIntervalSecs=1
restartSUTThreadProbability=0.0
keyingTimeMultiplier=0.8
thinkTimeMultiplier=0.8
traceTerminalIO=false
paymentWeight=0.0
orderStatusWeight=0.0
deliveryWeight=0.0
stockLevelWeight=0.0
storeWeight=0.0
rollbackPercent=0.0
reportScript=./generateReport.py -t report_simple.html
