#utf-8
#Wed Feb 12 00:27:16 UTC 2025
sys.k8scli=wy@133.133.135.56
sys.namespace=polardb1
sys.pods=pxc-product-spcl-dn-0-cands-0,pxc-product-spcl-dn-0-cands-1,pxc-product-spcl-dn-0-cands-2,pxc-product-spcl-dn-1-cands-0,pxc-product-spcl-dn-1-cands-1,pxc-product-spcl-dn-1-cands-2,pxc-product-spcl-cn-host-0-758d6cd84f-kg5rt, pxc-product-spcl-cn-host-1-7cdb5447cb-bx46k, pxc-product-spcl-cn-host-2-666d46478f-tpw2f
#sys.leaderzone=zone1
sys.zones=zone1
sys.zone1.pods=pxc-product-spcl-dn-0-cands-0,pxc-product-spcl-dn-0-cands-1,pxc-product-spcl-dn-0-cands-2,pxc-product-spcl-dn-1-cands-0,pxc-product-spcl-dn-1-cands-1,pxc-product-spcl-dn-1-cands-2,pxc-product-spcl-cn-host-0-758d6cd84f-kg5rt, pxc-product-spcl-cn-host-1-7cdb5447cb-bx46k, pxc-product-spcl-cn-host-2-666d46478f-tpw2f
sys.storage.pods=pxc-product-spcl-dn-0-cands-0,pxc-product-spcl-dn-0-cands-1,pxc-product-spcl-dn-0-cands-2,pxc-product-spcl-dn-1-cands-0,pxc-product-spcl-dn-1-cands-1,pxc-product-spcl-dn-1-cands-2
sys.compute.pods=pxc-product-spcl-cn-host-0-758d6cd84f-kg5rt, pxc-product-spcl-cn-host-1-7cdb5447cb-bx46k, pxc-product-spcl-cn-host-2-666d46478f-tpw2f
sys.faults=storage_all_io_fault_percent_80.yaml
sys.storage.volumePath=/data-log/mysql
sys.compute.volumePath=/home/admin/drds-server/logs
sys.faulttime=1
db=polardb
driver=com.mysql.cj.jdbc.Driver
application=Generic
conn=jdbc\:mysql\://133.133.135.56\:31151/tpccdb?useSSL\=false&useServerPrepStmts\=true&useConfigs\=maxPerformance&rewriteBatchedStatements\=true&cachePrepStmts\=true&prepStmtCacheSize\=1000&prepStmtCacheSqlLimit\=2048
user=root
password=123@Test
warehouses=100
loadWorkers=6
monkeys=8
sutThreads=32
maxDeliveryBGThreads=0
maxDeliveryBGPerWarehouse=0
rampupMins=2
rampupSUTMins=1
rampupTerminalMins=0
runMins=3
reportIntervalSecs=1
restartSUTThreadProbability=0.0
keyingTimeMultiplier=1
thinkTimeMultiplier=1
traceTerminalIO=false
paymentWeight=0.0
orderStatusWeight=0.0
deliveryWeight=0.0
stockLevelWeight=0.0
storeWeight=0.0
rollbackPercent=0.0
reportScript=./generateReport.py -t report_simple.html
