apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-fault-example
  namespace: chaos-testing
spec:
  action: fault
  mode: all
  selector:
    namespaces:
      - '$NAMESPACE'
    labelSelectors: '$PODNAME'
  volumePath: '$VOLUMEPATH'
  errno: 5
  percent: '$PERCENT'
  duration: '$DURATION'