apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: net-loss
  namespace: chaos-testing
spec:
  action: loss
  mode: all
  selector:
    pods:
      $NAMESPACE: '$INJECTPODS'
  loss:
    loss: '$LOSS'
  duration: '$DURATION'