apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: chaos-testing
spec:
  mode: all
  selector:
    pods:
      $NAMESPACE: '$INJECTPODS'
  stressors:
    cpu:
      workers: '$WORKERS'
      load: '$LOAD'
  duration: '$DURATION'