kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: cpu-stress
spec:
  mode: all
  action: stress-cpu
  address: '$INJECTIPS'
  stress-cpu:
    load: '$LOAD'
    workers: '$WORKERS'
  duration: '$DURATION'