apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - '$NAMESPACE'
    labelSelectors: '$PODNAME'
  delay:
    latency: '$LATENCY'
    correlation: '0'
    jitter: '0ms'
  duration: '$DURATION'