apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: fail-pod-by-labels
spec:
  experiments:
    - scope: pod
      target: pod
      action: fail
      desc: "inject fail image to  select pod"
      matchers:
        - name: labels
          value:
            - "$PODNAME"
        - name: namespace
          value:
            - "$NAMESPACE"
        - name: evict-count
          value:
            - "1"