kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: kill-process
spec:
  action: process
  address: '$INJECTIPS'
    # - http://133.133.135.157:31767
  mode: all
  process:
    process: '$PROCESS'
    signal: 9
  duration: '$DURATION'
