kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: io-fault
spec:
  action: disk-fill
  address: '$INJECTIPS'
  mode: all
  disk-fill:
    size: 10241G
    path: '$VOLUMEPATH'
    fill-by-fallocate: false
  duration: '$DURATION'