kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: net-delay
spec:
  action: network-delay
  address: '$INJECTIPS'
  mode: all
  network-delay:
    device: '$DEVICE'
    ip-protocol: all
    latency: '$LATENCY'
  duration: '$DURATION'