kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: net-loss
spec:
  action: network-loss
  address: '$INJECTIPS'
  mode: all
  network-loss:
    device: '$DEVICE'
    ip-protocol: all
    percent: '$LOSS'
  duration: '$DURATION'
