kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata: {namespace: chaos-testing, name: net-delay}
spec:
  action: network-delay
  address: ['http://133.133.135.156:31767']
  mode: all
  network-delay: {device: em1, ip-protocol: all, latency: 32ms}
  duration: 120s
